### PR TITLE
Fixed UI to behave more reliably when server is under heavy load

### LINKED ISSUE #63: Make problem summary requests asynchronous
When logged in as an instructor and viewing an open rapid response problem in LMS, our app polls the `/responses` endpoint every 3 seconds to get updated information about problem responses. While running load tests on rapid response problems (#16), it was discovered that server can take a long time to serve requests. This is a major UX problem as it can result in requests that run for a very long time (I observed times from 20s-1m) and completely lock up the UI in the meantime. We should change these requests to be asynchronous so the UI can at least remain interactive and the clock can continue ticking down. We should also set sensible timeouts for those requests

ss 2018-06-05 at 12 40 08

ss 2018-06-05 at 12 40 17

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?
Closes #63 

#### What's this PR do?
What the PR title says.

#### How should this be manually tested?
This will be a little bit complicated, and will probably involve running the load test. Come chat with me about this

#### Any background context you want to provide?
A note about why this PR is so big: All of the UI code up until now did not account for any kind of HTTP request error (timeouts most notably), and therefore we were able to assume a very simplistic UI state of "open" or "closed". In reality, any one of the HTTP requests can experience an error (timeouts under heavy load are easily reproduceable). Handling those errors, informing the user about delays, and properly controlling the dispatching of requests meant that a significant chunk of the front end logic had to be rewritten.

#### Screenshots (if appropriate)

*Initial load*

ss 2018-07-24 at 09 59 43

*Opening (before the toggle status endpoint returns a response)*

ss 2018-07-24 at 10 01 04

*Closing  (before the toggle status endpoint returns a response)*

ss 2018-07-24 at 10 01 32

*Closing  (after the toggle status endpoint returns a response)*

ss 2018-07-24 at 10 02 05

*Delayed response warning (while polling the responses endpoint)*

ss 2018-07-24 at 10 27 54

*Timeout (while polling the responses endpoint)*

ss 2018-07-24 at 17 00 05

*Timeout (after clicking to change the problem status, or on initial page load)*

ss 2018-07-24 at 10 12 30

### CODE REVIEW

**Comment by gsidebo** [comment]
@pdpinch @roberthouse54 Let me know what you think of the screenshots & the language used. Everything in these screenshots was added in this PR.

**Comment by pdpinch** [comment]
Language looks good to me, but the state descriptions don't quite match the screenshots. Are they in the right order?

Also, did you end up greying out the whole div as Rob suggested? For which states?

File: rapid_response_xblock/static/js/src/rapid.js [hunk 1]
```diff
@@ -52,38 +118,21 @@
 
     // default values
     var state = {
-      is_open: false,
+      // TODO: change back to false
```
Comment (noisecapella) [inline rapid_response_xblock/static/js/src/rapid.js]: What does this mean?
